language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
cache:
  directories:
    - '$HOME/.ivy2/cache'
branches:
  except:
    - master
before_script:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927"
  - "echo 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list"
  - "sudo apt-get update"
  - "sudo apt-get install -y mongodb-org=3.2.6 mongodb-org-server=3.2.6 mongodb-org-shell=3.2.6 mongodb-org-mongos=3.2.6 mongodb-org-tools=3.2.6"
  - "sleep 15" #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - "mongo --version"
