sudo: false
language: scala
matrix:
  include:
    - scala: 2.11.12
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.10
      env: PLAY_VERSION=2.6
      jdk: openjdk8
    - scala: 2.12.10
      env: PLAY_VERSION=2.7
      jdk: openjdk8

cache:
  directories:
    - '$HOME/.ivy2/cache'
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
branches:
  except:
    - master
